[package]
name = "pmindp-sensor"
version = "0.1.0"
edition = "2021"
authors = ["nand-nor <a13xandra.cliff0rd@gmail.com>"]

[dependencies]
embedded-hal = {version = "1.0"}

[features]
default=[]
std=[]